### ISSUE TITLE
start error with @monaco-editor/react/

### ISSUE THREAD

**Issue by architectpub** [archguard/archguard-frontend#23]
D:\project\archguard\archguard-frontend\archguard>yarn start
yarn run v1.22.19
warning package.json: No license field
$ umi dev
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Starting the development server...

× Webpack
  Compiled with some errors in 50.62s

 ERROR  Failed to compile with 1 errors                                                                                                               08:44:55

 error  in ./node_modules/@monaco-editor/react/dist/index.mjs

Module parse failed: Unexpected token (1:1806)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

Environment:
D:\project\archguard\archguard-frontend\archguard>node --version
v14.21.3

D:\project\archguard\archguard-frontend\archguard>npm --version
9.6.4

D:\project\archguard\archguard-frontend\archguard>yarn --version
1.22.19

**Comment by phodal** [comment]
follow https://github.com/archguard/archguard-frontend/blob/master/.github/workflows/ci.yml

using `npm` instead of `yarn`

**Comment by architectpub** [comment]
> follow https://github.com/archguard/archguard-frontend/blob/master/.github/workflows/ci.yml
> 
> using `npm` instead of `yarn`

Thanks .  I can start it ,but get following error :

umi.0139336c.js:1345 TypeError: E.map is not a function
    at it (umi.0139336c.js:3:158260)
    at Ga (umi.0139336c.js:1345:1825495)
    at Qs (umi.0139336c.js:1345:1846617)
    at ql (umi.0139336c.js:1345:1883987)
    at Wc (umi.0139336c.js:1345:1874473)
    at Gc (umi.0139336c.js:1345:1874401)
    at Hc (umi.0139336c.js:1345:1874254)
    at jc (umi.0139336c.js:1345:1870583)
    at Ac (umi.0139336c.js:1345:1869531)
    at O (umi.0139336c.js:1085:322106)
js @ umi.0139336c.js:1345
Rs.n.callback @ umi.0139336c.js:1345
Lo @ umi.0139336c.js:1345
Gl @ umi.0139336c.js:1345
Hl @ umi.0139336c.js:1345
Vl @ umi.0139336c.js:1345
Kc @ umi.0139336c.js:1345
Xc @ umi.0139336c.js:1345
Ac @ umi.0139336c.js:1345
O @ umi.0139336c.js:1085
j @ umi.0139336c.js:1085
_.<computed> @ umi.0139336c.js:1085
w @ umi.0139336c.js:1085
k @ umi.0139336c.js:1085
umi.0139336c.js:3 Uncaught TypeError: E.map is not a function
    at it (umi.0139336c.js:3:158260)
    at Ga (umi.0139336c.js:1345:1825495)
    at Qs (umi.0139336c.js:1345:1846617)
    at ql (umi.0139336c.js:1345:1883987)
    at Wc (umi.0139336c.js:1345:1874473)
    at Gc (umi.0139336c.js:1345:1874401)
    at Hc (umi.0139336c.js:1345:1874254)
    at jc (umi.0139336c.js:1345:1870583)
    at Ac (umi.0139336c.js:1345:1869531)
    at O (umi.0139336c.js:1085:322106)
it @ umi.0139336c.js:3
Ga @ umi.0139336c.js:1345
Qs @ umi.0139336c.js:1345
ql @ umi.0139336c.js:1345
Wc @ umi.0139336c.js:1345
Gc @ umi.0139336c.js:1345
Hc @ umi.0139336c.js:1345
jc @ umi.0139336c.js:1345
Ac @ umi.0139336c.js:1345
O @ umi.0139336c.js:1085
j @ umi.0139336c.js:1085
_.<computed> @ umi.0139336c.js:1085
w @ umi.0139336c.js:1085
k @ umi.0139336c.js:1085

**Comment by phodal** [comment]
follow https://github.com/archguard/archguard-frontend/blob/master/.github/workflows/ci.yml

and use Node.js 16

**Comment by architectpub** [comment]
> follow https://github.com/archguard/archguard-frontend/blob/master/.github/workflows/ci.yml
> 
> and use Node.js 16

Find the reason ,the frontend can only uses port 8080 .  I configure the port in 80 .
It causes that  http://localhost:8080/api/system-info return wrong response .
