### ISSUE TITLE
@monaco-editor : Module parse failed: Unexpected token (1:1806)

### ISSUE THREAD

**Issue by huiwenhan** [archguard/archguard-frontend#27]
ERROR in ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/common/utils.mjs 179:9-18
Can't import the named export 'P' from non EcmaScript module (only default export is available)
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/index.mjs
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/index.mjs
 @ ./node_modules/prosemirror-markdown/dist/index.js
 @ ./node_modules/rich-markdown-editor/dist/lib/ExtensionManager.js
 @ ./node_modules/rich-markdown-editor/dist/index.js
 @ ./src/pages/workbench/Workbench.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

ERROR in ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/common/utils.mjs 179:31-40
Can't import the named export 'S' from non EcmaScript module (only default export is available)
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/index.mjs
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/index.mjs
 @ ./node_modules/prosemirror-markdown/dist/index.js
 @ ./node_modules/rich-markdown-editor/dist/lib/ExtensionManager.js
 @ ./node_modules/rich-markdown-editor/dist/index.js
 @ ./src/pages/workbench/Workbench.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

ERROR in ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/index.mjs 81:9-21
Can't import the named export 'decode' from non EcmaScript module (only default export is available)
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/index.mjs
 @ ./node_modules/prosemirror-markdown/dist/index.js
 @ ./node_modules/rich-markdown-editor/dist/lib/ExtensionManager.js
 @ ./node_modules/rich-markdown-editor/dist/index.js
 @ ./src/pages/workbench/Workbench.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

ERROR in ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/index.mjs 81:44-56
Can't import the named export 'decode' from non EcmaScript module (only default export is available)
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/index.mjs
 @ ./node_modules/prosemirror-markdown/dist/index.js
 @ ./node_modules/rich-markdown-editor/dist/lib/ExtensionManager.js
 @ ./node_modules/rich-markdown-editor/dist/index.js
 @ ./src/pages/workbench/Workbench.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

ERROR in ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/common/utils.mjs 92:18-28
Can't import the named export 'decodeHTML' from non EcmaScript module (only default export is available)
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/index.mjs
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/index.mjs
 @ ./node_modules/prosemirror-markdown/dist/index.js
 @ ./node_modules/rich-markdown-editor/dist/lib/ExtensionManager.js
 @ ./node_modules/rich-markdown-editor/dist/index.js
 @ ./src/pages/workbench/Workbench.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

ERROR in ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/rules_inline/entity.mjs 36:22-32
Can't import the named export 'decodeHTML' from non EcmaScript module (only default export is available)
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/parser_inline.mjs
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/index.mjs
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/index.mjs
 @ ./node_modules/prosemirror-markdown/dist/index.js
 @ ./node_modules/rich-markdown-editor/dist/lib/ExtensionManager.js
 @ ./node_modules/rich-markdown-editor/dist/index.js
 @ ./src/pages/workbench/Workbench.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

ERROR in ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/index.mjs 60:9-21
Can't import the named export 'encode' from non EcmaScript module (only default export is available)
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/index.mjs
 @ ./node_modules/prosemirror-markdown/dist/index.js
 @ ./node_modules/rich-markdown-editor/dist/lib/ExtensionManager.js
 @ ./node_modules/rich-markdown-editor/dist/index.js
 @ ./src/pages/workbench/Workbench.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

ERROR in ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/index.mjs 60:22-34
Can't import the named export 'format' from non EcmaScript module (only default export is available)
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/index.mjs
 @ ./node_modules/prosemirror-markdown/dist/index.js
 @ ./node_modules/rich-markdown-editor/dist/lib/ExtensionManager.js
 @ ./node_modules/rich-markdown-editor/dist/index.js
 @ ./src/pages/workbench/Workbench.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

ERROR in ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/index.mjs 81:22-34
Can't import the named export 'format' from non EcmaScript module (only default export is available)
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/index.mjs
 @ ./node_modules/prosemirror-markdown/dist/index.js
 @ ./node_modules/rich-markdown-editor/dist/lib/ExtensionManager.js
 @ ./node_modules/rich-markdown-editor/dist/index.js
 @ ./src/pages/workbench/Workbench.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

ERROR in ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/index.mjs 44:17-28
Can't import the named export 'parse' from non EcmaScript module (only default export is available)
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/index.mjs
 @ ./node_modules/prosemirror-markdown/dist/index.js
 @ ./node_modules/rich-markdown-editor/dist/lib/ExtensionManager.js
 @ ./node_modules/rich-markdown-editor/dist/index.js
 @ ./src/pages/workbench/Workbench.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

ERROR in ./node_modules/prosemirror-markdown/node_modules/markdown-it/lib/index.mjs 64:17-28
Can't import the named export 'parse' from non EcmaScript module (only default export is available)
 @ ./node_modules/prosemirror-markdown/node_modules/markdown-it/index.mjs
 @ ./node_modules/prosemirror-markdown/dist/index.js
 @ ./node_modules/rich-markdown-editor/dist/lib/ExtensionManager.js
 @ ./node_modules/rich-markdown-editor/dist/index.js
 @ ./src/pages/workbench/Workbench.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

ERROR in ./node_modules/@monaco-editor/react/dist/index.mjs 1:1806
Module parse failed: Unexpected token (1:1806)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

**Comment by huiwenhan** [comment]
Node.js v18.19.0

**Comment by phodal** [comment]
follow github action to setup: https://github.com/archguard/archguard-frontend/blob/master/.github/workflows/ci.yml
