### ISSUE TITLE
Look me：ArchGuard 部署搭建 —— help ！！！

### ISSUE THREAD

**Issue by xuexiansen123** [archguard/archguard-frontend#3]
本人小白一枚，最近刚刚接触`ArchGuard`，在部署搭建过程中遇到一些问题，麻烦大佬们各显神通，救救小菜鸡。
以下操作按照`READ.ME`进行，如有理解不当，还请大家多多指教。
[ArchGuard scanner](https://github.com/archguard/scanner/) - scan source code, binary data and othes, and feed to database.
[ArchGuard frontend](https://github.com/archguard/archguard-frontend) - visualization results & dashboard
[ArchGuard backend](https://github.com/archguard/archguard) - connect scanner and show data.

### local setup
```
cd archguard
yarn install
yarn start
```
执行 `yarn start`后，打印日志
```
yarn run v1.22.18
$ umi dev
WARN [WARN] update `jsx: "react"` into `jsx: "react-jsx"` to suport the new JSX transform in React 17 in tsconfig.json
Starting the development server...

✔ Webpack
  Compiled successfully in 38.66s

 DONE  Compiled successfully in 38660ms                                                                                   4:30:18 PM


  App running at:
  - Local:   http://localhost:8080 (copied to clipboard)
  - Network: http://xxxxxxx:8080

启动时间有点慢，试试新出的 MFSU 方案，1s+ 完成启动，详见 https://github.com/umijs/umi/issues/6766
 WAIT  Compiling...                                                                                                       4:30:18 PM


✔ Webpack
  Compiled successfully in 2.07s

 DONE  Compiled successfully in 2069ms
```
将上述日志返回的`Network: http://xxxxxxx:8080`，在浏览器上方式时，日志出现错误信息
```
[HPM] Error occurred while trying to proxy request /api/system-info from localhost:8080 to http://localhost:8080 (EADDRNOTAVAIL) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/system-info from localhost:8080 to http://localhost:8080 (EADDRNOTAVAIL) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/system-info from localhost:8080 to http://localhost:8080 (EADDRNOTAVAIL) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
同时浏览器页面出现 `Request failed with status code 500` 错误
![image](https://user-images.githubusercontent.com/61086658/162417631-52b59a9f-cb47-4dbd-b712-5391ad551e93.png)

### docker setup
本地部署无果，遂尝试 docker 方式
```
cd archguard
docker build -t archguard-frontend:latest .
docker run -it --rm -p 3000:80 archguard-frontend:latest
```
执行`docker build -t archguard-frontend:latest .`，寻求大佬帮助说是`alpine`代理源问题，但是换了几个还是没有解决
![image](https://user-images.githubusercontent.com/61086658/162417069-a60ac3b0-d555-4392-b622-a5b7db7e8a3c.png)

**Comment by phodal** [comment]
本地搭建，需要先启动后端，再启动前端。
